version: "3.3"
services:
  java:
    container_name: java-training-docker
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/java-training
    networks:
      - docker_network
    stdin_open: true
    ports:
      - "4567:4567"

networks:
  docker_network:
    driver: bridge